### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by tempdeltavalue** [coledd/nn#1]
`C:\Users\temp_local\Desktop\nn>make`

cc -Wall nn.c -c -march=native -flto -Ofast -fPIC
process_begin: CreateProcess(NULL, cc -Wall nn.c -c -march=native -flto -Ofast -fPIC, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:12: nn.o] Error 2

**Comment by coledd** [comment]
Sorry, I have not tested this on Windows or MacOS. The training portion of this library was originally developed on Linux, and deployment aimed at embedded systems (MCUs). I will take a look to see what effort is required to make it cross-platform. Thanks for the notification!

**Comment by tempdeltavalue** [comment]
@coledd Thank you for a reply.

Also you have something strange with getline(&line, &len, file) in data_load

**Comment by coledd** [comment]
The compilation error is due to the generation of the shared library for the nn module. This is used by the python bindings. Sorry, but this project has only been designed for and tested using a Linux host.
